# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynmE8i7VlirMeXxRluYXc3SjFcCwB8A5
"""

print("Hello World")
print('Olá Mundo')

print("O professor Caio é 'super'")
print('O professor Caio é "super"')

print("Jefferson"+ " Martins")

nome = "Jefferson" #tipo String
sobrenome = "Martins"
peso = 72 #tipo integer
altura = 1.75 #tipo float
temTatto = True #tipo boolean


peso = str(peso)
print(nome + " " + sobrenome)
print("O " + nome + " tem " + peso + ' kilos')
print("Tem a altura de ", altura)
print("Eu tenho " + str(altura) + "cm")

valor01 = int(input("Insira o primeira valor: "))
valor02 = int(input("Insira o segundo valor: "))
texto = '''
    [1] Soma
    [2] Dividir
    [3] Multiplicar
    [4] Subtrair
  
'''
print (texto)
escolha = input("Qual operação deseja? ")
print(type(escolha))

if int(escolha) > 0:
  int(escolha)
else:
  str(escolha)

if escolha == 1 or escolha == "Soma":
  resultado = valor01 + valor02
  print("O resultado da soma é", resultado)

if escolha == 2 or escolha == "Dividir":
  resultado = valor01 / valor02
  print("O resultado da divisão é", resultado)

if escolha == 3 or escolha == "Multiplicar":
  resultado = valor01 * valor02
  print("O resultado da multiplicação é", resultado)

if escolha == 4 or escolha == "Subtrair":
  resultado = valor01 - valor02
  print("O resultado da subtração é", resultado)

lala = "Jefferson"
rodar = True
contador = 0

while rodar:
  print(lala)
  contador = contador + 1
  if contador >= 10:
    rodar = False

rodar = True
while rodar:
  nome = input("Qual o nome do aluno: ")
  nota01 = int(input("Informe a nota do 1º Bimestre: "))
  nota02 = int(input("Informe a nota do 2º Bimestre: "))
  nota03 = int(input("Informe a nota do 3º Bimestre: "))
  nota04 = int(input("Informe a nota do 4º Bimestre: "))
  mediaEscolar = 7
  mediaAluno = (nota01 + nota02 + nota03 + nota04)/4

  if mediaAluno >= mediaEscolar:
    print("O Aluno ", nome, " foi aprovado com média ", mediaAluno)
  else:
    print("O Aluno ", nome, " foi reprovado com média ", mediaAluno)
  
  resposta = (input("Você deseja testar outro aluno :  \nSim ou Não\n"))

  if resposta == "nao" or resposta =="não":
    rodar = False
  else:
    rodar = True

def minhaFuncao(lala,valor02):
  print("Jefferson")
  print("valor: ", lala, "e", valor02)

minhaFuncao(3,6)
minhaFuncao(2,4)
minhaFuncao(7,14)