# -*- coding: utf-8 -*-
"""Aula2-adivinhacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-r9x4ZL-FfvRMz_PhStDtaEPAiQ5pLrw
"""

from  random import randint

print("------Iniciando o Super Game ------")

tesouro = randint(0,100)
chute = 0
chances = 10

while chute != tesouro:
  chute = input("Qual numero você acha que é ")
  if chute.isnumeric():
    chute = int(chute)
    chances = chances -1
    if chute == tesouro:
      print('')
      print('Parabéns! Você acertou')
      print('O numero era {} e voce ainda tinha {} chances'.format(tesouro,chances))
      print('')
      break;
    else:
      print('')
      if chute > tesouro:
        print('Voce errou! Dica: É um numero menor!')
      else:
          print('Você errou! Fica: É um numero maior')
          print('Voce ainda ossui {} chances'.format(chances))
      if chances == 0 :
          print('')
          print(f'Suas chances acabaram. O nunmero era {tesouro}. Voce Perdeu')
          print('')
          break;
      else:
        print('')
        print('Voce inseriu letras. Só é permitido números')
        print(f'Voce ainda possuir {chances} chances')
        print('')
print("------ GAMER OVER ------")

      


'''
@param {type:"integer"} serve para incluir um parametro para modificação dos valores, ao inves de alterar o valor da variavel no código
'''
