# -*- coding: utf-8 -*-
"""CePython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkH4IpbByer0PA4ApGA98vRUwpEZpwOz
"""

viacep.com.br/ws/01001000/json/

import requests

def buscaCep():
  print("----------CEPYTHON 0.0.1----------")
  print("")
  repetir = True
  cep = "0"

  while repetir:
    
    if len(cep) < 8: #verifica se o tamanho da string CEP é igual a 8 caracteres
      cep = str(input('Digite um CEP com 8 digitos: '))
    else:    
      repetir = False  
      resultado = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
      endereco = resultado.json()
  
 
  if endereco=={'erro':True}: #Qdo o CEP é invalido, retornar mensagem de erro
    print("Não foi localizado nenhum endereço para o CEP informado")
  else:
    print("")
    print("==========>CEP ENCONTRADO<==========")
    print('CEP: {}'.format(endereco['cep']))
    print('Logradouro: {}'.format(endereco['logradouro']))
    print(f"Cidade: {endereco['localidade']} ")
    print('Estado: ', endereco['uf'])
    print("")
    
buscaCep()

rodar = True
while rodar:
  print("")
  nConsulta = int(input("Deseja efetuar nova consulta? \n1) Sim \n2) Não \n"))
  print("")
  if nConsulta == 1:
    buscaCep()
  else:
    rodar = False
    break;